import type { Node, Edge } from "@xyflow/react";
import type { NycNodeData, EnvGroupData } from "../types";
import { SCHEMA_MAP } from "./schemas";

// ═══════════════════════════════════════════════════════════════════════════════
//  Nyctus Demo: Student Marks Analysis
//  stdlib ONLY: no pip, no conda packages beyond python=3.11
//  ScriptNode  → generates /out/report.html (inline CSS chart)
//  GuiNode     → python3 -m http.server 8080 --directory /out
// ═══════════════════════════════════════════════════════════════════════════════

const CSV_CONTENT = `name,math,science,english\nAlice,88,92,76\nBob,74,68,85\nCarol,91,87,93\nDavid,66,79,72\nEva,95,88,91`;

// Generates a self-contained dark-theme HTML report using only stdlib
const ANALYSIS_SCRIPT = String.raw`import csv, json, pathlib, statistics

pathlib.Path("/out").mkdir(parents=True, exist_ok=True)
rows = list(csv.DictReader(open("/data/students.csv")))
subjects = ["math", "science", "english"]
colors   = {"math": "#818cf8", "science": "#22d3ee", "english": "#34d399"}

def grade(total):
    return ("A", "#34d399") if total >= 255 else \
           ("B", "#fbbf24") if total >= 225 else ("C", "#f87171")

cards = ""
for r in rows:
    scores  = {s: int(r[s]) for s in subjects}
    total   = sum(scores.values())
    g, gc   = grade(total)
    bars    = "".join(
        f'<div style="margin:4px 0">'
        f'<span style="display:inline-block;width:72px;color:#8b92ab;font-size:11px">{s}</span>'
        f'<span style="display:inline-block;height:12px;width:{scores[s]}%;'
        f'background:{colors[s]};border-radius:3px;vertical-align:middle"></span>'
        f'<span style="margin-left:6px;font-size:11px;color:#e8eaf0">{scores[s]}</span></div>'
        for s in subjects
    )
    cards += f'''
    <div style="background:#1a1e2a;border:1px solid #2a304a;border-radius:10px;padding:16px 20px;min-width:180px">
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px">
        <span style="font-weight:600;font-size:15px;color:#e8eaf0">{r["name"]}</span>
        <span style="background:{gc}22;color:{gc};border-radius:99px;padding:2px 10px;font-size:12px;font-weight:700">{g}</span>
      </div>
      {bars}
      <div style="margin-top:10px;font-size:11px;color:#8b92ab">Total: <b style="color:#e8eaf0">{total}</b></div>
    </div>'''

# Subject averages
avgs = {s: statistics.mean(int(r[s]) for r in rows) for s in subjects}
avg_bars = "".join(
    f'<div style="display:flex;align-items:center;gap:10px;margin:8px 0">'
    f'<span style="width:80px;font-size:12px;color:#8b92ab">{s}</span>'
    f'<div style="flex:1;height:18px;background:#13161e;border-radius:4px;overflow:hidden">'
    f'<div style="height:100%;width:{avgs[s]}%;background:{colors[s]};border-radius:4px;'
    f'transition:width .3s"></div></div>'
    f'<span style="width:36px;text-align:right;font-size:12px;color:#e8eaf0">{avgs[s]:.1f}</span>'
    f'</div>'
    for s in subjects
)

html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Student Marks · Nyctus</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
<style>*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:"Inter",sans-serif;background:#0d0f14;color:#e8eaf0;padding:32px;min-height:100vh}}
h1{{font-size:22px;font-weight:700;margin-bottom:4px}}
.badge{{background:#6366f122;color:#818cf8;border-radius:99px;padding:3px 12px;font-size:11px;font-weight:700;vertical-align:middle;margin-left:10px}}
</style></head>
<body>
<h1>📊 Student Marks <span class="badge">Nyctus · Python {__import__("sys").version.split()[0]} · stdlib only</span></h1>
<p style="color:#8b92ab;font-size:13px;margin:8px 0 28px">Generated by the Nyctus pipeline engine</p>

<div style="background:#13161e;border:1px solid #2a304a;border-radius:12px;padding:20px 24px;margin-bottom:28px;max-width:480px">
  <div style="font-size:13px;font-weight:600;color:#8b92ab;margin-bottom:14px;text-transform:uppercase;letter-spacing:.5px">Subject Averages</div>
  {avg_bars}
</div>

<div style="font-size:13px;font-weight:600;color:#8b92ab;margin-bottom:14px;text-transform:uppercase;letter-spacing:.5px">Student Breakdown</div>
<div style="display:flex;flex-wrap:wrap;gap:16px">{cards}</div>
</body></html>
"""

pathlib.Path("/out/index.html").write_text(html)
print("[nyctus] Generated /out/index.html")
`;

// ── Env group ────────────────────────────────────────────────────────────────
const ENV_GROUP: Node<EnvGroupData> = {
    id: "demo-env-1",
    type: "EnvGroupNode",
    position: { x: 20, y: 30 },
    style: { width: 900, height: 290 },
    zIndex: -1,
    data: {
        label: "Python 3.11 — stdlib only, no pip",
        envType: "micromamba",
        envName: "nyctus-demo",
        dependencies: ["python=3.11"],
        pip_deps: [],
        config: JSON.stringify({
            envType: "micromamba",
            envName: "nyctus-demo",
            pip_deps: [],
        }, null, 2),
        schema: SCHEMA_MAP.EnvGroupNode,
    },
};

const DATA_IN: Node<NycNodeData> = {
    id: "demo-1",
    type: "NycNode",
    parentId: "demo-env-1",
    extent: "parent",
    position: { x: 28, y: 115 },
    data: {
        label: "Students CSV",
        nodeType: "DataNode",
        icon: "◈",
        config: JSON.stringify({
            params: { filename: "students.csv", content: CSV_CONTENT, mount_path: "/data/students.csv" },
        }, null, 2),
        schema: SCHEMA_MAP.DataNode,
    },
};

const SCRIPT: Node<NycNodeData> = {
    id: "demo-2",
    type: "NycNode",
    parentId: "demo-env-1",
    extent: "parent",
    position: { x: 330, y: 100 },
    data: {
        label: "Generate Report",
        nodeType: "ScriptNode",
        icon: "⌨",
        config: JSON.stringify({
            type: "ScriptNode",
            label: "Generate Report",
            params: { runtime: "micromamba", env: "nyctus-demo", script: ANALYSIS_SCRIPT },
        }, null, 2),
        schema: SCHEMA_MAP.ScriptNode,
    },
};

const DASHBOARD: Node<NycNodeData> = {
    id: "demo-3",
    type: "NycNode",
    parentId: "demo-env-1",
    extent: "parent",
    position: { x: 640, y: 100 },
    data: {
        label: "Web Report",
        nodeType: "GuiNode",
        icon: "◎",
        config: JSON.stringify({
            type: "GuiNode",
            label: "Web Report",
            params: {
                framework: "http.server",
                port: 8765,
            },
        }, null, 2),
        schema: SCHEMA_MAP.GuiNode,
    },
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const DEMO_NODES: Node<any>[] = [ENV_GROUP, DATA_IN, SCRIPT, DASHBOARD];

export const DEMO_EDGES: Edge[] = [
    { id: "demo-e1", source: "demo-1", target: "demo-2", animated: true },
    { id: "demo-e2", source: "demo-2", target: "demo-3", animated: true },
];
